env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
rules:
  {
    no-console: off,
    operator-linebreak: 0,
    no-param-reassign: 0,
    no-useless-catch: off,
    global-require: 0,
    prefer-promise-reject-errors: off,
    implicit-arrow-linebreak: off,
    function-paren-newline: 0,
    no-await-in-loop: off,
    import/no-unresolved: off,
  }
